import os
from pathlib import Path
from datetime import datetime

class BusinessAuditor:
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.briefings_path = self.vault_path / "Briefings"
        self.briefings_path.mkdir(exist_ok=True)
        
    def run_audit(self):
        print("--- 📊 Starting Business Audit ---")
        
        # 1. Read Revenue Data (Simulated for Demo)
        revenue_mtd = 4500
        target = 10000
        
        # 2. Check Completed Tasks
        done_path = self.vault_path / "Done"
        completed_tasks = list(done_path.glob("*.md"))
        
        # 3. Check for Bottlenecks
        pending_approval = self.vault_path / "Pending_Approval"
        bottlenecks = list(pending_approval.glob("*.md"))
        
        # 4. Generate the Briefing
        today = datetime.now().strftime("%Y-%m-%d")
        briefing_content = f"""# Monday Morning CEO Briefing - {today}

## 🚀 Executive Summary
The system is operational. {len(completed_tasks)} tasks were completed this week. {len(bottlenecks)} items require your attention.

## 💰 Revenue Summary
- **MTD Total:** ${revenue_mtd:,.2f}
- **Target:** ${target:,.2f}
- **Progress:** {(revenue_mtd/target)*100:.1f}%

## ✅ Recently Completed Tasks
{self._format_list(completed_tasks)}

## ⚠️ Current Bottlenecks (Awaiting Approval)
{self._format_list(bottlenecks)}

## 💡 Proactive Suggestion
Based on the current task completion rate, we are on track to hit the revenue goal. However, approving the pending items in `/Pending_Approval` would accelerate this week's billing cycle.

---
*Generated by AI Employee v0.1*
"""
        briefing_file = self.briefings_path / f"{today}_Monday_Briefing.md"
        briefing_file.write_text(briefing_content, encoding="utf-8")
        print(f"✅ Briefing generated: {briefing_file}")
        
    def _format_list(self, files):
        if not files:
            return "- None"
        return "\n".join([f"- {f.stem}" for f in files[:5]])

if __name__ == "__main__":
    auditor = BusinessAuditor("AI_Employee_Vault")
    auditor.run_audit()
